import { Equal, Expect } from '@type-challenges/utils'

type cases = [
  Expect<Equal<Capitalize2<'foobar'>, 'Foobar'>>,
  Expect<Equal<Capitalize2<'FOOBAR'>, 'FOOBAR'>>,
  Expect<Equal<Capitalize2<'foo bar'>, 'Foo bar'>>,
  Expect<Equal<Capitalize2<''>, ''>>,
  Expect<Equal<Capitalize2<'a'>, 'A'>>,
  Expect<Equal<Capitalize2<'b'>, 'B'>>,
  Expect<Equal<Capitalize2<'c'>, 'C'>>,
  Expect<Equal<Capitalize2<'d'>, 'D'>>,
  Expect<Equal<Capitalize2<'e'>, 'E'>>,
  Expect<Equal<Capitalize2<'f'>, 'F'>>,
  Expect<Equal<Capitalize2<'g'>, 'G'>>,
  Expect<Equal<Capitalize2<'h'>, 'H'>>,
  Expect<Equal<Capitalize2<'i'>, 'I'>>,
  Expect<Equal<Capitalize2<'j'>, 'J'>>,
  Expect<Equal<Capitalize2<'k'>, 'K'>>,
  Expect<Equal<Capitalize2<'l'>, 'L'>>,
  Expect<Equal<Capitalize2<'m'>, 'M'>>,
  Expect<Equal<Capitalize2<'n'>, 'N'>>,
  Expect<Equal<Capitalize2<'o'>, 'O'>>,
  Expect<Equal<Capitalize2<'p'>, 'P'>>,
  Expect<Equal<Capitalize2<'q'>, 'Q'>>,
  Expect<Equal<Capitalize2<'r'>, 'R'>>,
  Expect<Equal<Capitalize2<'s'>, 'S'>>,
  Expect<Equal<Capitalize2<'t'>, 'T'>>,
  Expect<Equal<Capitalize2<'u'>, 'U'>>,
  Expect<Equal<Capitalize2<'v'>, 'V'>>,
  Expect<Equal<Capitalize2<'w'>, 'W'>>,
  Expect<Equal<Capitalize2<'x'>, 'X'>>,
  Expect<Equal<Capitalize2<'y'>, 'Y'>>,
  Expect<Equal<Capitalize2<'z'>, 'Z'>>,
]
